fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt.git"
      ref: '4.2.0'
    powershell: "https://github.com/puppetlabs/puppetlabs-powershell.git"
    archive: "https://github.com/voxpupuli/puppet-archive.git"
  symlinks:
    filebeat: "#{source_dir}"
