name: Run pdk static validation

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Run pdk validate
      uses: puppets-epic-show-theatre/action-pdk-validate@v1
      with:
        puppet-version: ""
        # [optional]
        # A string indicating the Puppet version to validate against, such as "5.4.2" or "5.5".
        pe-version: ""
        # [optional]
        # A string indicating the PE version to validate against, such as "2017.3.5" or "2018.1".
